### ISSUE TITLE
Problem with WHERE activepoints >= 25000.000000000000;

### ISSUE THREAD

**Issue by PurpleSunnrise** [joshcam/PHP-MySQLi-Database-Class#171] opened 2014-11-26 09:22 UTC
I have a problem with this query

$status = 1;
$rallyTimeStart = 1396346265;
$rallyPointsMinRAP = 25000.000000000000;

$cols = Array();
$cols = Array("uid", "recruiterUID", "nickname", "registrationTime", "activepoints");
$db->where ("activepoints", $rallyPointsMinRAP, ">=");
$db->orderBY ("recruiterUID", "ASC");
$dataRecruiter = $db->get ("user", null, $cols);	
foreach ($dataRecruiter as $referal){
 echo ''.$referal['uid'].'<br />';
}

The field is activepoints in the database is Decimal(30,12).
There are only give results about 25000.000000000001;

**Comment by avbdr** [comment] 2015-08-06 08:09
closing as not a bug

**Closed by avbdr** 2015-08-06 08:09 UTC
