### ISSUE TITLE
Erros Join underline columns

### ISSUE THREAD

**Issue by jjalvesneto** [joshcam/PHP-MySQLi-Database-Class#348] opened 2015-10-27 20:31 UTC
the relationships of my tables defaults ( table_primarykey ) , Unidades_id , Pessoas_id , Enderecos_id when the class is preparing sql it is removing the "_" and the "s" generating "SELECT * FROM LEFT JOIN inventory units on estoques.unidadeid = unidades.id WHERE estoques.id = 5 LIMIT 1 "instead of " SELECT * FROM LEFT JOIN inventory units on estoques.Unidades_id = WHERE unidades.id estoques.id = 5 LIMIT 1 "as I could get around considering that I can not change the name of my table columns?

**Comment by avbdr** [comment] 2015-10-27 21:48
you can use $db->join("users u", "p.tenantID=u.tenantID", "LEFT");

**Comment by jjalvesneto** [comment] 2015-10-29 02:23
There is no way to make the library does not modify the column names , eg always stay Unidades_id and not unidadeid 😐

**Comment by avbdr** [comment] 2015-10-29 06:55
Can you post code sample? I'm not sure what you are taking about

**Comment by avbdr** [comment] 2015-10-29 09:12
if you are talking about dbObject, then you can use $model->join('joinmodel', 'primary_Key')

**Comment by avbdr** [comment] 2015-11-15 09:30
closing as not a bug

**Closed by avbdr** 2015-11-15 09:30 UTC
