### ISSUE TITLE
insertMulti onDuplicate.

### ISSUE THREAD

**Issue by salatproduction** [joshcam/PHP-MySQLi-Database-Class#571] opened 2017-01-01 15:25 UTC
subj.
```
$array = [];
for ($i = 0; count($array) < 10000; $i++) {
    array_push($array, ["data"=> $i, "date" => $db->now()]);
}
$db->onDuplicate(["data", "date"], "id");
$db->insertMulti("array", $query);

P.S.
I dunno why, but insertMulti truncates inserting table.
```

**Comment by avbdr** [comment] 2017-08-08 15:21
duplicate of #657

**Closed by avbdr** 2017-08-08 15:21 UTC
